package com.example.ui.localization

object Strings {
    fun get(key: String, lang: String): String {
        val isArabic = lang == "ar"
        return when (key) {
            "app_title" -> if (isArabic) "لوحة قماشية للقصص" else "Story Canvas"
            "settings" -> if (isArabic) "الإعدادات" else "Settings"
            "language" -> if (isArabic) "اللغة / Language" else "Language"
            "dark_mode" -> if (isArabic) "الوضع الداكن" else "Dark Mode"
            "light_mode" -> if (isArabic) "الوضع الفاتح" else "Light Mode"
            "theme" -> if (isArabic) "المظهر (ليل / نهار)" else "Theme (Dark / Light)"
            "new_canvas" -> if (isArabic) "إنشاء مخطط قصة جديد" else "Create New Canvas"
            "my_projects" -> if (isArabic) "مشاريع القصص" else "Story Projects"
            "search_projects" -> if (isArabic) "البحث في المشاريع..." else "Search projects..."
            "project_title" -> if (isArabic) "عنوان المشروع" else "Project Title"
            "project_desc" -> if (isArabic) "وصف المشروع" else "Project Description"
            "cancel" -> if (isArabic) "إلغاء" else "Cancel"
            "create" -> if (isArabic) "إنشاء" else "Create"
            "add_node" -> if (isArabic) "إضافة عنصر / بلاطة" else "Add Block / Tile"
            "connect" -> if (isArabic) "ربط" else "Connect"
            "minimap" -> if (isArabic) "خريطة مصغرة" else "Minimap"
            "search_nodes" -> if (isArabic) "بحث في الصناديق..." else "Search nodes..."
            "node_title" -> if (isArabic) "عنوان الصندوق" else "Box Title"
            "node_content" -> if (isArabic) "المحتوى التفصيلي" else "Detailed Content"
            "node_type" -> if (isArabic) "نوع العنصر" else "Element Type"
            "tags" -> if (isArabic) "الوسوم (مفصولة بفواصل)" else "Tags (comma separated)"
            "color" -> if (isArabic) "اللون" else "Color"
            "sketch" -> if (isArabic) "رسم / سكتش" else "Sketch / Drawing"
            "open_subcanvas" -> if (isArabic) "فتح مساحة فرعية داخلية" else "Open Inner Sub-Canvas"
            "subcanvas_workspace" -> if (isArabic) "مساحة العمل الفرعية للقصة" else "Inner Sub-Canvas Workspace"
            "infinite_canvas" -> if (isArabic) "مخطط قصة غير محدود" else "Infinite Story Canvas"
            "presentation_mode" -> if (isArabic) "وضع العرض التقديمي" else "Presentation Mode"
            "structures" -> if (isArabic) "الهياكل والتخطيط الآلي" else "Auto-Layout Structures"
            "mindmap_layout" -> if (isArabic) "تخطيط الخريطة الذهنية" else "Mind Map Layout"
            "tree_structure" -> if (isArabic) "الهيكل الشجري" else "Tree Structure"
            "timeline_sequence" -> if (isArabic) "تسلسل الخط الزمني" else "Timeline Sequence"
            "export_markdown" -> if (isArabic) "تصدير المستند (ماركداون)" else "Export Story Outline (Markdown)"
            "export_dialog_title" -> if (isArabic) "تصدير مستند القصة" else "Export Story Document"
            "export_dialog_desc" -> if (isArabic) "انسخ القصة المنسقة مع الفصول وملفات الشخصيات بصيغة Markdown:" else "Copy your structured story document, chapters, and character profiles in Markdown format:"
            "copy_to_clipboard" -> if (isArabic) "نسخ إلى الحافظة" else "Copy to Clipboard"
            "close" -> if (isArabic) "إغلاق" else "Close"
            "save" -> if (isArabic) "حفظ" else "Save"
            "delete" -> if (isArabic) "حذف" else "Delete"
            "duplicate" -> if (isArabic) "نسخ" else "Duplicate"
            "back" -> if (isArabic) "رجوع" else "Back"
            "chapter" -> if (isArabic) "فصل" else "Chapter"
            "event" -> if (isArabic) "حدث" else "Event"
            "character" -> if (isArabic) "شخصية" else "Character"
            "idea" -> if (isArabic) "فكرة" else "Idea"
            "conclusion" -> if (isArabic) "خاتمة" else "Conclusion"
            "main_topic" -> if (isArabic) "الموضوع الرئيسي" else "Main Topic"
            "subtopic" -> if (isArabic) "موضوع فرعي" else "Subtopic"
            "kingdom" -> if (isArabic) "مملكة / عالم" else "Kingdom"
            "ability" -> if (isArabic) "قدرة / سحر" else "Ability"
            "secret" -> if (isArabic) "سر / غموض" else "Secret"
            "timeline" -> if (isArabic) "خط زمني" else "Timeline"
            "select_connect_target" -> if (isArabic) "اختر الصندوق المراد ربطه" else "Select target box to connect"
            "sample_project_title" -> if (isArabic) "ملحمة عوالم أستريا" else "Astraea Chronicles"
            "sample_project_desc" -> if (isArabic) "مخطط مانجا خيالي وبناء عوالم مع مستندات الفصول الكاملة." else "Epic Manga & Worldbuilding Mindmap with Full Chapter Documents"
            "hero_subtitle" -> if (isArabic) "ابدأ مساحة عمل غير محدودة للقصص وبناء العوالم" else "Start an infinite story & worldbuilding workspace"
            "no_projects_msg" -> if (isArabic) "لا توجد مشاريع حالياً. اضغط أعلاه لإنشاء مخطط قصة جديد." else "No projects found. Tap above to create a new canvas."
            "delete_project_title" -> if (isArabic) "حذف المشروع" else "Delete Project"
            "delete_project_confirm" -> if (isArabic) "هل أنت تأكد من رغبتك في حذف هذا المشروع؟" else "Are you sure you want to delete this project?"
            "preset_architecture" -> if (isArabic) "بنية القصة المجهزة" else "Story Preset Architecture"
            "preset_manga" -> if (isArabic) "مانجا وبناء عوالم خيالية" else "Manga & Fantasy Worldbuilding"
            "preset_3act" -> if (isArabic) "هيكل الحبكة من 3 أجزاء" else "3-Act Plot Structure"
            "preset_character" -> if (isArabic) "شبكة ومصفوفة الشخصيات" else "Character Web & Matrix"
            "preset_chapter" -> if (isArabic) "الجدول الزمني للفصول" else "Chapter Chronology & Timeline"
            "music_player" -> if (isArabic) "مشغل الموسيقى والمؤثرات" else "Ambient Music Player"
            "no_track" -> if (isArabic) "لا يوجد مقطع صوتي محدد" else "No track selected"
            "loop_favorites" -> if (isArabic) "تكرار قائمة المفضلة تلقائياً" else "Loop Favorites Playlist"
            "import_local_audio" -> if (isArabic) "استيراد ملفات صوتية محلياً" else "Import Local Music Files"
            "playlist" -> if (isArabic) "قائمة التشغيل" else "Playlist"
            "grid_snap" -> if (isArabic) "محاذاة للشبكة (Grid Snap)" else "Snap to Grid"
            "grid_visible" -> if (isArabic) "إظهار خطوط الشبكة" else "Show Grid Lines"
            "ambient_glow" -> if (isArabic) "توهج الخلفية المحيطي" else "Ambient Glow"
            "ambient_glow_color" -> if (isArabic) "لون التوهج المحيطي" else "Ambient Glow Color"
            "sfx_enabled" -> if (isArabic) "المؤثرات الصوتية التفاعلية (SFX)" else "Sound Effects (SFX)"
            "tilemap_toolbar" -> if (isArabic) "أدوات الشبكة والتحكم" else "Grid & Control Dock"
            "reset_zoom" -> if (isArabic) "إعادة التكبير" else "Reset Zoom"
            "smart_node_settings" -> if (isArabic) "إعدادات الصندوق الذكي" else "Smart Node Settings"
            "open_full_doc" -> if (isArabic) "فتح مستند طويل كامل الصفحة" else "Open Full-Page Document Note"
            "chars_written" -> if (isArabic) "حرفاً مكتوباً" else "characters written"
            "dedicated_writing_studio" -> if (isArabic) "استوديو كتابة كامل مرتبط بهذا الصندوق" else "Dedicated long-form writing studio linked to this node"
            "short_summary" -> if (isArabic) "ملخص قصير" else "Short Summary"
            "node_category" -> if (isArabic) "فئة نوع العنصر" else "Node Type Category"
            "marker_badge" -> if (isArabic) "شارة الأيقونة" else "Marker Badge"
            "completion_progress" -> if (isArabic) "نسبة الإنجاز" else "Completion Progress"
            "date_chapter_label" -> if (isArabic) "التاريخ / رقم الفصل" else "Date / Chapter #"
            "boundary_group" -> if (isArabic) "مجموعة الحدود" else "Boundary Group"
            "story_presentation" -> if (isArabic) "العرض التقديمي للقصة" else "Story Presentation"
            "exit_presentation" -> if (isArabic) "خروج من العرض" else "Exit Presentation"
            "slide" -> if (isArabic) "شريحة" else "Slide"
            "of" -> if (isArabic) "من" else "of"
            "no_nodes_present" -> if (isArabic) "لا توجد صناديق في المخطط للعرض." else "No nodes in canvas to present."
            "detailed_note" -> if (isArabic) "الملاحظة / المستند التفصيلي:" else "Detailed Note / Document:"
            "previous" -> if (isArabic) "السابق" else "Previous"
            "next" -> if (isArabic) "Next" else "Next"
            "auto_play" -> if (isArabic) "تشغيل تلقائي" else "Auto Play"
            "draw_sketch_here" -> if (isArabic) "ارسم السكتش هنا..." else "Draw your sketch here..."
            "clear" -> if (isArabic) "مسح" else "Clear"
            "doc_subtitle" -> if (isArabic) "مستند" else "Document"
            "saving" -> if (isArabic) "جاري الحفظ..." else "Saving..."
            "saved" -> if (isArabic) "تم الحفظ ✓" else "Saved ✓"
            "search_in_doc" -> if (isArabic) "البحث داخل المستند..." else "Search inside document..."
            "story_templates" -> if (isArabic) "قوالب القصة الجاهزة" else "Story Templates"
            "template_character" -> if (isArabic) "بطاقة تعريف الشخصية" else "Character Profile Sheet"
            "template_scene" -> if (isArabic) "مخطط المشهد والفصل" else "Chapter & Scene Outline"
            "template_world" -> if (isArabic) "بناء العالم ونظام السحر" else "Worldbuilding & Magic System"
            "copy_text" -> if (isArabic) "نسخ النص" else "Copy text"
            "matches" -> if (isArabic) "تطابق" else "matches"
            "close_search" -> if (isArabic) "إغلاق البحث" else "Close search"
            "words" -> if (isArabic) "كلمة" else "words"
            "chars" -> if (isArabic) "حرف" else "chars"
            "min_read" -> if (isArabic) "دقيقة قراءة" else "min read"
            "done_writing" -> if (isArabic) "تمت الكتابة ✓" else "Done Writing ✓"
            "write_placeholder" -> if (isArabic) "ابدأ كتابة فصلك أو تفاصيل عالمك هنا...\nاستخدم شريط الأدوات أعلاه للعناوين والقوائم وقوالب القصة." else "Start writing your chapter, character lore, or story details here...\n\nUse the toolbar above for headings, lists, or story templates."
            "full_doc_attached" -> if (isArabic) "تم إرفاق مستند كامل ✓" else "Full Document Attached ✓"
            "parent_topic" -> if (isArabic) "موضوع أعلى (أب)" else "Parent Topic"
            "sibling_topic" -> if (isArabic) "موضوع موازي (شقيق)" else "Sibling Topic"
            "floating_topic" -> if (isArabic) "عنصر عائم مستقل" else "Floating Topic"
            "boundary" -> if (isArabic) "إطار حدودي" else "Boundary"
            "summary" -> if (isArabic) "عنصر ملخص" else "Summary"
            "callout" -> if (isArabic) "ملاحظة شارحة (Callout)" else "Callout Note"
            "export_json" -> if (isArabic) "تصدير خريطة JSON" else "Export MindMap JSON"
            "themes" -> if (isArabic) "مظاهر الخريطة (Themes)" else "Map Themes"
            "focus_mode" -> if (isArabic) "وضع التركيز (Focus)" else "Focus Mode"
            "exit_focus" -> if (isArabic) "إلغاء التركيز" else "Exit Focus"
            "multi_select" -> if (isArabic) "تحديد متعدد" else "Multi-Select Mode"
            "clear_select" -> if (isArabic) "مسح التحديد" else "Clear Selection"
            "bulk_delete" -> if (isArabic) "حذف العناصر المحددة" else "Delete Selected"
            "bulk_color" -> if (isArabic) "تغيير لون المحدد" else "Color Selected"
            "quick_actions" -> if (isArabic) "إجراءات سريعة" else "Quick Actions"
            "relationship" -> if (isArabic) "علاقة مخصصة" else "Relationship"
            "fishbone" -> if (isArabic) "مخطط هيكل السمكة" else "Fishbone Diagram"
            "matrix" -> if (isArabic) "مصفوفة الجدول" else "Matrix Layout"
            "tree_table" -> if (isArabic) "جدول شجري" else "Tree Table"
            "logic_chart" -> if (isArabic) "مخطط منتقي أفقي" else "Logic Chart"
            "org_chart" -> if (isArabic) "الهيكل التنظيمي" else "Org Chart"
            else -> key
        }
    }

    fun translateNodeType(type: String, lang: String): String {
        if (lang != "ar") return type
        return when (type) {
            "Main Topic" -> "الموضوع الرئيسي"
            "Subtopic" -> "موضوع فرعي"
            "Parent Topic" -> "موضوع أب"
            "Floating" -> "موضوع عائم"
            "Callout" -> "ملاحظة شارحة"
            "Summary" -> "ملخص"
            "Character" -> "شخصية"
            "Chapter" -> "فصل"
            "Event" -> "حدث"
            "Kingdom" -> "مملكة / عالم"
            "Ability" -> "قدرة / سحر"
            "Secret" -> "سر / غموض"
            "Timeline" -> "خط زمني"
            "Idea" -> "فكرة"
            "Conclusion" -> "خاتمة"
            else -> type
        }
    }
}
